name: leukocyte-vit-yolo
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.5
  - torchvision=0.20
  - torchaudio=2.5
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - tqdm
  - pip
  - pip:
      - timm==1.0.11
      - ultralytics==8.3.33
      - torchmetrics==1.8.2
      - albumentations==1.4.21
      - statsmodels
