model:
  name: vit_base_patch16_384
  pretrained: true

training:
  batch_size: 16   
  epochs: 50
  learning_rate: 1e-5
  optimizer: adam
  scheduler:
    type: StepLR
    step_size: 15
    gamma: 0.1
  early_stopping:
    patience: 5

data:
  input_size: 384
  kfold_splits: 5
  sampler: weighted_random
